title: "My ML Portfolio"
description: "ML personal portfolio showcasing projects and blog posts."
baseurl: "" 
url: "https://github.com/ArangurenAndres/arangurenandres.github.io"
theme: minima

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - blog.md

collections:
  projects:
    output: true
    permalink: "/projects/:path/"

# Socials (optional)
github_username: "ArangurenAndres"
linkedin_username: "andres-aranguren"
email: "aranguren.andres9712@gmail.com"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
