# Site settings
title: Andres Aranguren - ML Portfolio
email: aranguren.andres9712@gmail.com
description: A modern showcase of my machine learning projects, blog posts, and professional journey.
baseurl: "" # e.g., /portfolio if hosted on a subdirectory
url: "https://arangurenandres.github.io" # Update to your GitHub Pages URL
twitter_username: arangurenandres
github_username: ArangurenAndres

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Helps with search engine optimization
  - jekyll-sitemap # Automatically generates a sitemap for your site


header_pages:
  - index.md
  - projects.md
  - blog.md

# Include custom CSS file
include: 
  - assets/css/style.css

# Excluded files and folders
exclude:
  - node_modules/
  - vendor/

# Social media links for easy updates in the future
social_links:
  github: https://github.com/ArangurenAndres
  twitter: https://twitter.com/arangurenandres
  linkedin: https://www.linkedin.com/in/andres-aranguren
